<a href="https://colab.research.google.com/github/snlramya0071/Assignment_2/blob/main/stocks_data_download.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/nodesense/cts-data-engineering-feb-2022/main/stocks/cm02MAR2022bhav.csv")
df.head()

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN,Unnamed: 13
0,20MICRONS,EQ,70.10,73.60,70.1,71.85,72.05,71.20,219912,15831255.05,02-MAR-2022,2642,INE144J01027,NaN
1,21STCENMGM,EQ,29.60,29.60,29.6,29.60,29.60,30.20,1209,35786.40,02-MAR-2022,45,INE253B01015,NaN
2,3IINFOLTD,EQ,51.05,51.35,49.1,49.45,49.40,51.45,1092731,54642699.40,02-MAR-2022,7273,INE748C01038,NaN
3,3MINDIA,EQ,21480.00,21480.00,20730.0,20923.10,20925.00,21208.40,1823,38294455.75,02-MAR-2022,1120,INE470A01017,NaN
4,3PLAND,BE,15.90,16.15,14.8,15.50,15.65,15.55,8318,128580.00,02-MAR-2022,70,INE105C01023,NaN

In [2]:
df1 = pd.read_csv("https://raw.githubusercontent.com/nodesense/cts-data-engineering-feb-2022/main/stocks/cm03MAR2022bhav.csv")
df1.head()

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN,Unnamed: 13
0,20MICRONS,EQ,73.05,74.60,71.20,72.00,72.50,71.85,129491,9434366.05,03-MAR-2022,1930,INE144J01027,NaN
1,21STCENMGM,EQ,29.05,30.15,29.05,29.05,29.05,29.60,75325,2214069.65,03-MAR-2022,266,INE253B01015,NaN
2,3IINFOLTD,EQ,49.60,50.95,49.60,50.00,50.10,49.45,629446,31659396.15,03-MAR-2022,5532,INE748C01038,NaN
3,3MINDIA,EQ,20905.00,21234.95,20731.75,21081.30,21080.00,20923.10,1066,22421795.00,03-MAR-2022,816,INE470A01017,NaN
4,3PLAND,BE,15.00,16.00,15.00,15.50,15.50,15.50,3129,49320.55,03-MAR-2022,64,INE105C01023,NaN

In [3]:
df2 = pd.read_csv("https://raw.githubusercontent.com/nodesense/cts-data-engineering-feb-2022/main/stocks/cm04MAR2022bhav.csv")
df2.head()

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN,Unnamed: 13
0,20MICRONS,EQ,72.00,72.80,70.10,71.60,71.9,72.00,95527,6.841018e+06,04-MAR-2022,1545,INE144J01027,NaN
1,21STCENMGM,EQ,28.50,28.50,28.50,28.50,28.5,29.05,1306,3.722100e+04,04-MAR-2022,39,INE253B01015,NaN
2,3IINFOLTD,EQ,50.95,52.50,49.50,52.50,52.5,50.00,1099713,5.709576e+07,04-MAR-2022,4308,INE748C01038,NaN
3,3MINDIA,EQ,20840.00,21045.35,20215.10,20379.35,20380.0,21081.30,5957,1.218543e+08,04-MAR-2022,3810,INE470A01017,NaN
4,3PLAND,BE,15.85,16.25,14.75,15.60,15.6,15.50,3123,4.914135e+04,04-MAR-2022,49,INE105C01023,NaN

In [4]:
df3 = pd.read_csv("https://raw.githubusercontent.com/nodesense/cts-data-engineering-feb-2022/main/stocks/cm07MAR2022bhav.csv")
df3.head()

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN,Unnamed: 13
0,20MICRONS,EQ,69.95,71.00,68.45,69.80,70.40,71.60,140616,9.823167e+06,07-MAR-2022,1742,INE144J01027,NaN
1,21STCENMGM,EQ,27.95,27.95,27.95,27.95,27.95,28.50,793,2.216435e+04,07-MAR-2022,34,INE253B01015,NaN
2,3IINFOLTD,EQ,52.25,55.10,51.00,55.10,55.10,52.50,1209245,6.554553e+07,07-MAR-2022,6644,INE748C01038,NaN
3,3MINDIA,EQ,20199.35,20199.35,19600.00,19925.95,19935.00,20379.35,15772,3.150913e+08,07-MAR-2022,2416,INE470A01017,NaN
4,3PLAND,BE,15.60,15.85,14.90,15.05,15.05,15.60,3548,5.421025e+04,07-MAR-2022,51,INE105C01023,NaN

In [5]:
df4 = pd.read_csv("https://raw.githubusercontent.com/nodesense/cts-data-engineering-feb-2022/main/stocks/cm09MAR2022bhav.csv")
df4.head()

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN,Unnamed: 13
0,20MICRONS,EQ,72.5,73.8,72.00,72.35,72.7,71.55,98968,7.190676e+06,09-MAR-2022,1556,INE144J01027,NaN
1,21STCENMGM,EQ,26.9,27.9,26.90,26.90,26.9,27.40,27666,7.482134e+05,09-MAR-2022,144,INE253B01015,NaN
2,3IINFOLTD,EQ,60.7,60.7,60.70,60.70,60.7,57.85,141465,8.586926e+06,09-MAR-2022,838,INE748C01038,NaN
3,3MINDIA,EQ,20180.0,20180.0,19826.55,19953.15,19950.0,19902.05,19116,3.809880e+08,09-MAR-2022,2441,INE470A01017,NaN
4,3PLAND,BE,16.0,16.0,15.75,15.90,15.9,15.25,3682,5.865170e+04,09-MAR-2022,52,INE105C01023,NaN

In [6]:
df.to_csv("March_02.csv")
df1.to_csv("March_03.csv")
df2.to_csv("March_04.csv")
df3.to_csv("March_07.csv")
df4.to_csv("March_09.csv")
#Export as download if in colab
from google.colab import files
# dfPivotSubdirURL.to_csv(brandname + '-subdirs_from_sitemap.csv', sep='\t')
files.download('March_02.csv')
files.download('March_03.csv')
files.download('March_04.csv')
files.download('March_07.csv')
files.download('March_09.csv')